# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    environment: test
    runs-on: [ubuntu-latest, windows-latest]

    strategy:
      matrix:
        node-version: [18.x, 19x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: create-db
    - run: npm run publish -- --ids=1322705852017659911 intro="test \n https://example.com" -m wait=20
    - run: npm run publish -- --ids=1322705852017659911,1549322039445659649 wait=20
