name: Testing

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '**/README.md'
    - '**/*.yml'
jobs:
  build:
    environment: test
    env:
      NODE_ENV: dev
      URL: ${{secrets.URL}}
      TOKEN: ${{secrets.TOKEN}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 19.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx ts-node ./src/index.ts  --ids 1384527253367894016 1602785768770084866  -m --wait 20
